CREATE TABLE CATEGORY (
    ID INT(11) NOT NULL AUTO_INCREMENT
  , NAME VARCHAR(100) NOT NULL
  , PRIMARY KEY (ID)
);

CREATE TABLE BOOK (
    ID INT(11) NOT NULL AUTO_INCREMENT
  , CATEGORY_ID INT(11) NOT NULL
  , ISBN VARCHAR(10) NOT NULL
  , TITLE VARCHAR(500) NOT NULL
  , PRICE FLOAT NOT NULL
  , PRIMARY KEY (ID)
  , CONSTRAINT FK_BOOK
    FOREIGN KEY (CATEGORY_ID)
    REFERENCES CATEGORY (ID)
    ON DELETE CASCADE
);

CREATE TABLE AUTHOR (
    ID INT(11) NOT NULL AUTO_INCREMENT
  , FIRST_NAME VARCHAR(60) NOT NULL
  , LAST_NAME VARCHAR(60) NOT NULL
  , DESCRIPTION VARCHAR(1200) NOT NULL
  , PRIMARY KEY (ID)
);

CREATE TABLE AUTHOR_BOOK (
  AUTHOR_ID INT(11) NOT NULL
  , BOOK_ID INT(11) NOT NULL
  , PRIMARY KEY(AUTHOR_ID, BOOK_ID)
  , CONSTRAINT FK_AUTHOR_BOOK_1 FOREIGN KEY (AUTHOR_ID)
      REFERENCES AUTHOR (ID) ON DELETE CASCADE
  , CONSTRAINT FK_AUTHOR_BOOK_2 FOREIGN KEY (BOOK_ID)
    REFERENCES BOOK (ID)
);